// CUSTOMIZE: This is the static, hand-scripted data that powers the
// credential-free NEXT_PUBLIC_REPLAY_MODE=1 deploy (e.g. the public Vercel
// build) -- every event, timestamp, and provider comparison below is fixed
// ahead of time, not generated by a live agent or LLM call. If you're
// adapting this template to your own agent/scenario, replace the contents
// of this file (REPLAY_BEATS, the provider candidates, REPLAY_KICKOFF_PROMPT,
// etc.) with data that matches your own agent's actual flow -- lib/useReplay.ts
// just plays back whatever beats/events you put here, so it doesn't need to
// change.
//
// Static data for the public "replay" site (NEXT_PUBLIC_REPLAY_MODE=1).
// Per the original design decision: the public site plays back a fixed,
// recorded-shaped run rather than exposing a live "Run Live" button to
// anonymous visitors against a real or mutable-in-memory backend. This file
// is the single source of truth for that run -- no server state, no API
// calls, safe to deploy to Vercel's serverless functions (which don't
// guarantee shared memory across invocations the way `next dev`'s single
// process does).
//
// Scenario: an enterprise support/trust-and-safety agent triages flagged
// tickets during the day -- verifying details via real x402-payable research
// APIs, and placing a real x402-payable phone call when warranted. Every
// provider below is real and independently confirmed to support x402
// payments: Tavily (docs.tavily.com/documentation/machine-payments/x402),
// Parallel.ai (parallelmpp.dev), and StablePhone (stablephone.dev, real
// disclosed price of $0.54/call). The one illustrative price is
// StablePhone's "priority" human-transfer tier -- that specific tiered price
// isn't publicly disclosed, so it's a reconstruction on the same real host,
// same disclosure convention as everything else illustrative in this file.
//
// The whole run is stamped onto a single mocked calendar day (2026-07-08,
// 9am-10pm) rather than "just now" timestamps, so the Activity Feed and Audit
// Trail read as a realistic day of a periodic monitoring agent's activity
// instead of a few seconds of wall-clock time.
import type { LedgerEntry } from "./t3n";

export interface ProviderCandidate {
  host: string;
  provider: string;
  category: string;
  /** omitted for candidates that can't actually be paid -- see `ineligible` */
  price?: number;
  /** true if the agent ruled this one out before pricing even mattered (e.g. no x402 support) */
  ineligible?: boolean;
  ineligibleReason?: string;
}

export interface ReplayEvent {
  ts: string; // ISO timestamp on the mocked replay day, always rendered in UTC
  type: "thinking" | "tool_call" | "tool_result" | "comparing_providers" | "payment_approved" | "payment_denied" | "user_reply";
  candidates?: ProviderCandidate[];
  selectedHost?: string;
  reason?: string;
  /** true on the first event after a visitor clicks Revoke -- lets the chat panel surface it as an operator action. */
  revokedNotice?: boolean;
  [key: string]: unknown;
}

export interface ReplayBeat {
  narration: string;
  events: ReplayEvent[];
  /** ms to hold after this beat's events finish, before the next beat starts */
  holdMs: number;
  /** if true, playback stops after this beat until the visitor clicks to continue */
  pauseForRevoke?: boolean;
}

const REPLAY_DAY = "2026-07-08";
const t = (time: string) => `${REPLAY_DAY}T${time}.000Z`;

const TAVILY_URL = "https://api.tavily.com/search";
const PARALLEL_URL = "https://api.parallel.ai/v1beta/tasks/runs";
const STABLEPHONE_URL = "https://stablephone.dev/api/v1/call";
// Illustrative -- same real host/provider as STABLEPHONE_URL, but the
// human-transfer "priority" tier's exact price isn't publicly disclosed.
const STABLEPHONE_PRIORITY_URL = "https://stablephone.dev/api/v1/call/priority";

// Officially reserved fictional US phone number range (555-0100 to
// 555-0199) -- guarantees nothing in this replay implies a real number is
// ever dialed.
const FAKE_PHONE_NUMBER = "+1-555-0142";

const TAVILY: ProviderCandidate = { host: "api.tavily.com", provider: "Tavily", category: "WEB_RESEARCH", price: 0.015 };
const PARALLEL: ProviderCandidate = { host: "api.parallel.ai", provider: "Parallel", category: "WEB_RESEARCH", price: 0.018 };
const STABLEPHONE: ProviderCandidate = { host: "stablephone.dev", provider: "StablePhone", category: "COMMUNICATIONS", price: 0.54 };
// Twilio is a real voice API, but it has no x402 support -- there's no way
// for an autonomous agent wallet to pay it per call, only pre-provisioned
// account billing. It's shown ruled out, not priced, since price was never
// the deciding factor.
const TWILIO: ProviderCandidate = {
  host: "twilio.com",
  provider: "Twilio",
  category: "COMMUNICATIONS",
  ineligible: true,
  ineligibleReason: "No x402 support",
};

export const REPLAY_POLICY = {
  per_call_cap: 0.6,
  session_budget: 1.0,
  host_allowlist: ["api.tavily.com", "api.parallel.ai", "stablephone.dev"],
};

// The standing instruction that justifies the agent's autonomous, periodic
// check-ins below -- shown as the opening message in the chat panel.
export const REPLAY_KICKOFF_PROMPT =
  "Keep an eye on flagged support tickets today. Verify what you can before acting, and call to confirm if it's warranted -- check with me before anything above the usual per-call cap.";

export const REPLAY_BEATS: ReplayBeat[] = [
  {
    narration: "9:04 AM -- a new ticket comes in: #4821, flagged high-risk. The agent starts researching before anything happens.",
    events: [
      {
        ts: t("09:04:00"),
        type: "thinking",
        text: "A new ticket just came in -- #4821, flagged high-risk: the customer is requesting an urgent refund and an address change. Let me see what I can verify before anything happens.",
      },
      { ts: t("09:04:02"), type: "tool_call", tool: "search_services", args: { keyword: "business identity verification" } },
      {
        ts: t("09:04:03"),
        type: "tool_result",
        tool: "search_services",
        result: { data: { items: [{ resource: TAVILY_URL }, { resource: PARALLEL_URL }] } },
      },
      {
        ts: t("09:04:05"),
        type: "comparing_providers",
        candidates: [TAVILY, PARALLEL],
        selectedHost: TAVILY.host,
        reason: "Tavily is the cheaper of the two verified research options ($0.015) -- starting there.",
      },
    ],
    holdMs: 2400,
  },
  {
    narration: "It inspects Tavily to confirm price and method, then pays.",
    events: [
      { ts: t("09:04:08"), type: "tool_call", tool: "inspect_service", args: { service_url: TAVILY_URL } },
      { ts: t("09:04:09"), type: "tool_result", tool: "inspect_service", result: { data: { status: "payable", price: { formatted: "$0.015 USDC" } } } },
    ],
    holdMs: 1400,
  },
  {
    narration: "First real payment: $0.015 to Tavily to cross-reference ticket #4821's details.",
    events: [
      { ts: t("09:04:11"), type: "tool_call", tool: "pay_for_service", args: { service_url: TAVILY_URL, method: "POST", amount_usdc: 0.015 } },
      { ts: t("09:04:12"), type: "payment_approved", service_url: TAVILY_URL, amount_usdc: 0.015, remaining_budget: 0.985 },
    ],
    holdMs: 2000,
  },
  {
    narration: "1:32 PM -- a second, independent check on ticket #4821, for corroboration.",
    events: [
      { ts: t("13:32:00"), type: "tool_call", tool: "inspect_service", args: { service_url: PARALLEL_URL } },
      { ts: t("13:32:01"), type: "tool_result", tool: "inspect_service", result: { data: { status: "payable", price: { formatted: "$0.018 USDC" } } } },
      { ts: t("13:32:03"), type: "tool_call", tool: "pay_for_service", args: { service_url: PARALLEL_URL, method: "POST", amount_usdc: 0.018 } },
      { ts: t("13:32:04"), type: "payment_approved", service_url: PARALLEL_URL, amount_usdc: 0.018, remaining_budget: 0.967 },
    ],
    holdMs: 2400,
  },
  {
    narration:
      "4:10 PM -- both research checks on ticket #4821 came back inconclusive on their own. Before placing a verification call, the agent checks which providers can actually take an agent-initiated payment.",
    events: [
      { ts: t("16:10:00"), type: "tool_call", tool: "search_services", args: { keyword: "phone call verification" } },
      {
        ts: t("16:10:01"),
        type: "tool_result",
        tool: "search_services",
        result: { data: { items: [{ resource: STABLEPHONE_URL }, { resource: "https://twilio.com" }] } },
      },
      {
        ts: t("16:10:03"),
        type: "comparing_providers",
        candidates: [STABLEPHONE, TWILIO],
        selectedHost: STABLEPHONE.host,
        reason: "Twilio doesn't support x402 -- there's no way for an autonomous agent wallet to pay it per call. StablePhone does, so it's the only real option here.",
      },
    ],
    holdMs: 2000,
  },
  {
    narration: "It inspects StablePhone to confirm price and method, then places the call -- $0.54, inside the $0.60 per-call cap.",
    events: [
      { ts: t("16:10:07"), type: "tool_call", tool: "inspect_service", args: { service_url: STABLEPHONE_URL } },
      { ts: t("16:10:08"), type: "tool_result", tool: "inspect_service", result: { data: { status: "payable", price: { formatted: "$0.54 USDC" } } } },
      {
        ts: t("16:10:10"),
        type: "tool_call",
        tool: "pay_for_service",
        args: {
          service_url: STABLEPHONE_URL,
          method: "POST",
          amount_usdc: 0.54,
          payload: { to: FAKE_PHONE_NUMBER, reason: "identity verification callback" },
        },
      },
      { ts: t("16:10:12"), type: "payment_approved", service_url: STABLEPHONE_URL, amount_usdc: 0.54, remaining_budget: 0.427 },
      {
        ts: t("16:10:16"),
        type: "thinking",
        text: "The call connected and rang for a while, but no one picked up. I'll note that the number couldn't be reached and flag ticket #4821 for a human to follow up on.",
      },
    ],
    holdMs: 2600,
  },
  {
    narration:
      "6:47 PM -- wow moment 1: a second ticket, #5390, is serious enough to warrant an escalated call with a live transfer to a compliance specialist -- priced at $0.89, above the $0.60 per-call cap. The agent tries anyway.",
    events: [
      {
        ts: t("18:47:00"),
        type: "thinking",
        text: "A second ticket just came in -- #5390: a new account requesting a large wire transfer to an unverified recipient, also flagged high-risk. This one's serious enough to warrant a live transfer to a compliance specialist.",
      },
      { ts: t("18:47:02"), type: "tool_call", tool: "inspect_service", args: { service_url: STABLEPHONE_PRIORITY_URL } },
      { ts: t("18:47:03"), type: "tool_result", tool: "inspect_service", result: { data: { status: "payable", price: { formatted: "$0.89 USDC" } } } },
      { ts: t("18:47:05"), type: "thinking", text: "That's pricier, but given the flag on this account, I think it's worth it. I'll attempt the call." },
      {
        ts: t("18:47:07"),
        type: "tool_call",
        tool: "pay_for_service",
        args: {
          service_url: STABLEPHONE_PRIORITY_URL,
          method: "POST",
          amount_usdc: 0.89,
          payload: { to: FAKE_PHONE_NUMBER, transfer_to_human: true },
        },
      },
      {
        ts: t("18:47:08"),
        type: "payment_denied",
        service_url: STABLEPHONE_PRIORITY_URL,
        amount_usdc: 0.89,
        reason: "policy_denied: 0.89 exceeds per-call cap 0.6",
      },
    ],
    holdMs: 2600,
  },
  {
    narration: "The agent adapts -- reports the denial honestly, then asks the operator directly what to do next.",
    events: [
      {
        ts: t("18:47:11"),
        type: "thinking",
        text: "That escalation call was denied by the spend policy. I've got two independent checks on ticket #4821 and a call attempt that didn't reach anyone -- I've left that one with a human. For ticket #5390, the escalation call needs to go above the per-call cap. Want me to keep going, or should you revoke my access here?",
      },
    ],
    holdMs: 1600,
    pauseForRevoke: true,
  },
  {
    narration: "9:58 PM -- wow moment 2: the operator revokes the agent's access before its next scheduled run. Its very next payment attempt fails instantly.",
    events: [
      { ts: t("21:58:00"), type: "tool_call", tool: "pay_for_service", args: { service_url: TAVILY_URL, method: "POST", amount_usdc: 0.015 }, revokedNotice: true },
      { ts: t("21:58:01"), type: "payment_denied", service_url: TAVILY_URL, amount_usdc: 0.015, reason: "host/http.egress_denied: agent access has been revoked" },
    ],
    holdMs: 2000,
  },
];

// The timestamp stamped on the visitor's own kickoff message -- same moment
// as the agent's first scheduled check-in, since nothing happens until they
// send it.
export const REPLAY_KICKOFF_TS = REPLAY_BEATS[0].events[0].ts;

export function ledgerEntryFromEvent(event: ReplayEvent, seq: number): LedgerEntry | null {
  if (event.type !== "payment_approved" && event.type !== "payment_denied") return null;
  return {
    seq,
    ts: new Date(event.ts).getTime(),
    service_url: String(event.service_url ?? ""),
    amount_usdc: Number(event.amount_usdc ?? 0),
    status: event.type === "payment_approved" ? "paid" : "denied",
    reason: event.reason ? String(event.reason) : undefined,
    remaining_budget: event.remaining_budget !== undefined ? Number(event.remaining_budget) : undefined,
    idempotency_key: `replay-${seq}`,
  };
}
